#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

~/.fehbg

redshift -l 48.139:11.566 &
dropbox &

xset -dpms
xset s 0
xset r rate 220 30

setxkbmap eu
setxkbmap -option caps:ctrl_modifier
numlockx on


xrandr --output DVI-I-1 --mode 1920x1080 --rate 60.00
xrandr --output DVI-D-0 --mode 1920x1080 --rate 119.98 --right-of DVI-I-1

eval "$(ssh-agent)"

exec awesome 
